apiVersion: v1
kind: Service
metadata:
  name: api-test-helper
  labels:
    component: api-test-helper
    tier: backend
spec:
  type: NodePort
  selector:
    component: api-test-helper
    tier: backend
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30001
