apiVersion: apps/v1
kind: Deployment
metadata:
  name: samaquiz-api
  labels:
    component: samaquiz-api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: samaquiz-api
      tier: backend
  template:
    metadata:
      labels:
        component: samaquiz-api
        tier: backend
    spec:
      containers:
        - name: samaquiz-api
          image: samaquiz-api.prod
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: samaquiz-api-config
            - configMapRef:
                name: db-app-config
            - configMapRef:
                name: sendgrid-config
