apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  serviceName: 'postgresql'
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          imagePullPolicy: 'IfNotPresent'
          envFrom:
            - configMapRef:
                name: db-config
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgres-volume-mount
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pvc
