apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-db-pv
  labels:
    type: local
    app: postgresql
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/data'
